/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ebp_proto_CONSTANTS_H
#define ebp_proto_CONSTANTS_H

#include "ebp_proto_types.h"



class ebp_protoConstants {
 public:
  ebp_protoConstants();

};

extern const ebp_protoConstants g_ebp_proto_constants;



#endif
