/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ebp_proto_constants.h"



const ebp_protoConstants g_ebp_proto_constants;

ebp_protoConstants::ebp_protoConstants() {
}



